### ISSUE TITLE
[Python 3.12] Fails with `ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/lib/python3.12/asyncio/__init__.py). Did you mean: 'coroutines'?`

### ISSUE THREAD

**Issue by dreirund** [ShadowBlip/ryzenadj-controller#2]
Ahoj,

I try to use this on Python 3.12.

It fails with `ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/lib/python3.12/asyncio/__init__.py). Did you mean: 'coroutines'?`:  
```
Traceback (most recent call last):
  File "/usr/bin/ryzenadj-controller", line 5, in <module>
    from ryzenadj_controller.ryzenadj_controller import main
  File "/usr/lib/python3.12/site-packages/ryzenadj_controller/ryzenadj_controller.py", line 5, in <module>
    from asyncio import (all_tasks, CancelledError, coroutine, create_task,
ImportError: cannot import name 'coroutine' from 'asyncio' (/usr/lib/python3.12/asyncio/__init__.py). Did you mean: 'coroutines'?
```

Is there any specific dependency missing, or is it an issue with never python version that needs adaption of your code?

Regards!

**Comment by pastaq** [comment]
Yeah, I basically abandoned this project because python-asyncio deprecated and removed coroutine, which ran the main loop. It could probably be fixed up if you want to take over the project. I'm going to archive this one.
